name: Main
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
jobs:
  push-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: v3.18.0

    - name: Chart Release
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login "${{ env.REGISTRY }}" --password-stdin -u "${{ github.actor }}"

        helm push helm/endpoint-copier-operator "oci://${{ env.REGISTRY }}/charts"
